FROM adoptopenjdk/openjdk14

COPY auth/build/libs/auth-0.0.1-SNAPSHOT.jar auth.jar

ENTRYPOINT java -jar auth.jar \
    --spring.data.mongodb.host=$MONGODB_HOST \
    --spring.data.mongodb.port=$MONGODB_PORT \
    --spring.data.mongodb.username=$MONGODB_USERNAME \
    --spring.data.mongodb.password=$MONGODB_PASSWORD \
    --spring.data.mongodb.database=$MONGODB_DATABASE \
    --spring.data.mongodb.replica-set-name=$MONGODB_REPLICA_SET \
    --uni.wdai.auth.secret_key=$AUTH_SECRET_KEY \
    --uni.wdai.auth.admin.secret_key=$AUTH_ADMIN_SECRET_KEY