FROM adoptopenjdk/openjdk14 as build

ADD . .

RUN ./gradlew :api:bootJar

FROM adoptopenjdk/openjdk14

COPY --from=build api/build/libs/api-0.0.1-SNAPSHOT.jar api.jar

ENTRYPOINT java -jar api.jar \
    --uni.wdai.s3.input_bucket=$S3_INPUT_BUCKET \
    --uni.wdai.s3.output_bucket=$S3_OUTPUT_BUCKET \
    --uni.wdai.sqs.start_queue=$SQS_QUEUE \
    --spring.data.mongodb.host=$MONGODB_HOST \
    --spring.data.mongodb.port=$MONGODB_PORT \
    --spring.data.mongodb.username=$MONGODB_USERNAME \
    --spring.data.mongodb.password=$MONGODB_PASSWORD \
    --spring.data.mongodb.database=$MONGODB_DATABASE